import os

RAW_DB_FILENAME = "RAW_DB.JSON"
SONG_DB_FILENAME = "ALLSONGS.JSON"
GAMES_DB_FILENAME = "ALLGAMES.JSON"
RV_DB_FILENAME = "REVERSE_DB.JSON"
DB_FILENAME = "DB.JSON"

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))