import os

RAW_DB_FILENAME = "RAW_DB.JSON"
DB_FILENAME = "DB.JSON"
CONSTRAINTS_FILENAME = "CONSTRAINTS.JSON"

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

MINIMUM_SOLUTION_POSSIBILITES = 1
GAME_GENERATION_TIMEOUT_S = 1

DEBUG = True

PB_WRAP_LEN = 14
CONSTRAINT_WRAP_LEN = 20